### ISSUE TITLE
Failing test on R-3.2.0 (RHEL 7)

### ISSUE THREAD

**Issue by wlandau** [richfitz/storr#101]
```r
test-hash.R:6: failure: serialize, dropping R version
identical(s1, s2) isn't false.
```

Fails on R-3.2.0 with 27508231b3c061afed9bb243d4422f81291f2e94 and 80f33d9458cab7aa40aaf31cbbd52f40d1659117. Succeeds on R-3.3.0. I have not looked at the details yet.

**Comment by richfitz** [comment]
Obsolete by #98 as we depend on 3.3.0 now
