### ISSUE TITLE
"github_release_storr_get" gone?

### ISSUE THREAD

**Issue by wcornwell** [richfitz/storr#12]
```
Error in plant_lookup_get(version) : 
  could not find function "github_release_storr_get"
```

did something change in storr?

**Comment by richfitz** [comment]
Yes, kind of everything sorry :(

See https://github.com/traitecoevo/taxonlookup/issues/16 for workaround. Should be fixed in a week or so...

**Comment by richfitz** [comment]
Fixed in less time than guestimated.  That has to be a first.
