### ISSUE TITLE
st$set() leaking space when setting same key again?

### ISSUE THREAD

**Issue by torfason** [richfitz/storr#128]
I was surprised to see that it looks like using `st$set("my_key", value)` does _not_ overwrite old objects stored under the same key from the storage backend. So the values just accumulate. I've tested it with both `SQLite` and `rds`. Thus, the following code results in either a 10MB `.sqlite` file with 1002 rows (one extra for some internal usage I'm guessing) for the `SQLite` backend, or a `data` file with 1001 `.rds`files, totaling 1.2MB (compression I guess). Can this really be the case?

Test code below:

```r
set.seed(42)
s$set("single_key", sample(letters, 1000, replace = TRUE))  # Only one line/file in data
for (i in 1:1000) {
  s$set("single_key", sample(letters, 1000, replace = TRUE))  # 1001 lines/files in data
}
```

I initalized using the following:

RDS:
```r
s <- storr::storr_rds("test_storr.rds")
```

SQLite:
```r
s <- storr::storr_dbi("storr_data", "storr_keys", RSQLite::SQLite(),"test_storr.sqlite")
```

Even `s$clear()` does not seem to remove the data?

**Comment by torfason** [comment]
Ooops!

I just figured out about the `s$gc()` function. I should have read the manual more closely, I was just not looking for this implementation detail, which would be crucial for my use case. Sorry about the noise ...

**Comment by richfitz** [comment]
Glad you found it :)
