### ISSUE TITLE
storr@refactor

### ISSUE THREAD

**Issue by wcornwell** [richfitz/storr#19]
```R
devtools::install_github("richfitz/storr@refactor")
```

Isn't working anymore for some reason, leads to this error:

```R
Downloading GitHub repo richfitz/storr@refactor
from URL https://api.github.com/repos/richfitz/storr/zipball/refactor
No encoding supplied: defaulting to UTF-8.
Error: lexical error: invalid char in json text.
                                       Not Found
                     (right here) ------^
```

This means that `taxonlookup` and `baad` instillation instructions don't work...

**Comment by richfitz** [comment]
I deleted the refactor branch because it was rolled into the master (and is now on CRAN).  I've updated all the instructions I could find that point at the old ref.
