### ISSUE TITLE
Running out of memory writing to cache with storr_rds

### ISSUE THREAD

**Issue by ateucher** [richfitz/storr#25]
Hi @richfitz, thanks so much for this package, it's coming in really handy. I have an issue though with a large file (3GB csv 55 columns, 10 million rows), where it's running out of memory writing it to the cache. I'm running Windows 7 64 bit, with 24 GB of memory.

``` r
download.file("https://pub.data.gov.bc.ca/datasets/949f2233-9612-4b06-92a9-903e817da659/ems_sample_results_historic_expanded.zip", destfile = "test.zip")
csv_file <- unzip("test.zip")
file.rename(csv_file, "test_storr.csv")
```

``` r
sessionInfo()
```

```
## R version 3.3.1 (2016-06-21)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 7 x64 (build 7601) Service Pack 1
## 
## locale:
## [1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252   
## [3] LC_MONETARY=English_Canada.1252 LC_NUMERIC=C                   
## [5] LC_TIME=English_Canada.1252    
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## loaded via a namespace (and not attached):
##  [1] magrittr_1.5       formatR_1.4        tools_3.3.1       
##  [4] htmltools_0.3.5    yaml_2.1.13        Rcpp_0.12.6       
##  [7] stringi_1.1.1      rmarkdown_1.0.9001 knitr_1.13        
## [10] stringr_1.0.0      digest_0.6.9       evaluate_0.9
```

``` r
library(storr)
packageVersion("storr")
```

```
## [1] '1.0.1'
```

``` r
library(readr)

dat <- read_csv("test_storr.csv")
dim(dat)
```

```
## [1] 10518573       55
```

``` r
object.size(dat)
```

```
## 4644497248 bytes
```

``` r
cache <- storr::storr_rds(tempfile())
cache$set("my_data", dat)
```

```
## Warning in writeBin(value[seq(i, min(j, len))], con): Reached total
## allocation of 24371Mb: see help(memory.size)

## Warning in writeBin(value[seq(i, min(j, len))], con): Reached total
## allocation of 24371Mb: see help(memory.size)

## Warning in writeBin(value[seq(i, min(j, len))], con): Reached total
## allocation of 24371Mb: see help(memory.size)

## Warning in writeBin(value[seq(i, min(j, len))], con): Reached total
## allocation of 24371Mb: see help(memory.size)

## Error: cannot allocate vector of size 8.0 Gb
```

``` r
cache$list()
```

```
## character(0)
```

``` r
cache$destroy()
```

I tested just writing the file with `saveRDS` and it worked just fine, so I dug through the source code of `storr` and saw that you are using `writeBin` internally instead of `saveRDS`. I also noticed that `storr` used to use `saveRDS` until [this commit](https://github.com/richfitz/storr/commit/01e446d7fbd3f8c004694b6f34dab210706452f5). So I installed from github to the commit before that, and it worked:

``` r
devtools::install_github("richfitz/storr", 
                         ref = "73505843261c23d092cff82613a0e8c5bd6f9d1f", quiet = TRUE)
library(storr)
packageVersion("storr")
```

```
## [1] '0.6.0'
```

``` r
library(readr)

dat <- read_csv("test_storr.csv")
dim(dat)
```

```
## [1] 10518573       55
```

``` r
object.size(dat)
```

```
## 4644497248 bytes
```

``` r
cache <- storr::storr_rds(tempfile())
cache$set("my_data", dat)
cache$list()
```

```
## [1] "my_data"
```

**Comment by ateucher** [comment]
And actually, if I uncomment [this test](https://github.com/richfitz/storr/blob/master/tests/testthat/test-driver-rds.R#L81) and run the tests, it fails:

```
==> devtools::test()

Loading storr
Loading required package: testthat
Testing storr
drivers [environment]: ..................................
export [environment]: ..........................................
external [environment]: .................
storr [environment]: ...................................................
drivers [rds]: ..................................
export [rds]: ..........................................
external [rds]: .................
storr [rds]: ...................................................
base64: ..
driver rds details: ......................WW1....
environment driver: .....
utils: .

Warnings -----------------------------------------------------------------------
1. large vector support (@test-driver-rds.R#99) - Reached total allocation of 24371Mb: see help(memory.size)

2. large vector support (@test-driver-rds.R#99) - Reached total allocation of 24371Mb: see help(memory.size)

Failed -------------------------------------------------------------------------
1. Error: large vector support (@test-driver-rds.R#99) -------------------------
'Calloc' could not allocate memory (2147483646 of 1 bytes)
1: dr$set_object(hash, x) at C:\_dev\storr/tests/testthat/test-driver-rds.R:99
2: write_bin(value, con) at C:\_dev\storr/R/driver_rds.R:147
3: writeBin(value[seq(i, min(j, len))], con) at C:\_dev\storr/R/utils.R:127
```

**Comment by richfitz** [comment]
Hi Andy - thanks for this! It came through while I was on holiday.  I'll try and replicate soon and see what the story is.

**Comment by ateucher** [comment]
Thanks @richfitz! Let me know what I can do.

**Comment by richfitz** [comment]
I have a fix for this!  It's not pretty but it should work.  I'll get it pushed to github soon (it's mixed in with a big overhaul of the package), but can you let me know if you'd be able to test it once it's up?

**Comment by fmichonneau** [comment]
I just ran into this, and I'm willing to be a guinea pig on the overhaul.

**Comment by richfitz** [comment]
What on earth are y'all storing? :)

Storing really big objects is always going to be really nasty; I'll try and post my experimentation with timings, but a to-disk roundtrip is going to cost ~25s for a file right on the 2GB limit.

**Comment by fmichonneau** [comment]
BIG DATA!

It'll be faster than having to recompute them, so I can deal with it :sunglasses:

**Comment by ateucher** [comment]
I'm happy to test as well. Thanks @richfitz

**Comment by richfitz** [comment]
I wonder if using feather for data frames might be faster (though I'd not want to add that dependency here). I saw a benchmark recently that found them *way* faster to store very large data.frames in.  It'd be a bit of an issue though because they'd not roundtrip correctly always (not everything can be losslessly converted to feather).

**Comment by ateucher** [comment]
I've been using feather a bit and it's *really* fast, and did definitely wonder about a storr backend using it (though obviously only for data frames). The only thing I wish it supported but doesn't (yet?) is list columns.

**Comment by richfitz** [comment]
Please have a look at the `develop` branch. You should be able to install that with `remotes::install_github("richfitz/storr@develop"`

**Comment by ateucher** [comment]
Worked for me! 4 minutes on the same machine and file as above (but I wouldn't use my computer as a good benchmark 😉 )

**Comment by richfitz** [comment]
Great, thanks! I'll look into what, if anything, can be done to speed that up with your particular file

**Comment by richfitz** [comment]
OK, I see times (user, system, elapsed, in seconds)

* Read with `readr::read_csv()`: 55 / 15 / 71s
* serialisation: 24 / 20 / 45
* hash: 17.6 / 0 / 17.6
* set object: 75 / 12 / 89
* get object: 59 / 8 / 69

So that's all pretty terrible :)  Total time for a roundtrip here is looking to be about 4.5 minutes and my computer is not a slouch (but still just a desktop PC).

R is really struggling to do _anything_ with that object, though; just computing `object.size` takes 15 seconds.

For comparison, I see 18.5s to write a feather file (elapsed) and 19.6s to read it in.  That's clearly much better than the 89 / 69s with rds, but we'd still have to pay the cost of serialisation and hash just to determine that we have a "big" object.  And the objects as returned aren't identical, or all.equal (attributes are re-ordered).  However, they do appear to be equivalent.

I'm not really sure what can be sensibly done to make this less unpleasant but I think we're fundamentally hitting the limits of what is sensible to do in an in-memory data.frame.  Let me know if you have any ideas, otherwise I'll just leave this as-is, I think.

**Comment by ateucher** [comment]
@richfitz I think you're absolutely right. For this particular data I did switch to using a sqlite backend (not with storr, but it looks like you might be moving to that direction?). But your work fixing this issue is still really helpful, so thanks!

**Comment by richfitz** [comment]
The SQLite support in the development version of storr is not meant to replace database-based table access; for that you want to use RSQLite and friends directly.  The new support allows storing individual keys in a table.  They're not really the same sort of thing as if you used SQL based storage with storr to keep your 3GB table you'd still be serialising it into a big opaque blob of data and pushing it into a system that wants to deal with tables!  Different tools for different problems, really.

I'm glad you got everything working and sorry this took so long to fix.

**Comment by ateucher** [comment]
Yep, that makes sense and I kind of thought that was what the SQLite support was for. Thanks, and no worries!
