### ISSUE TITLE
Depends on development RSQLite

### ISSUE THREAD

**Issue by richfitz** [richfitz/storr#28]
This blocks a CRAN release.  Depending on timing, either

* add a compatibility layer for `driver_dbi$set_object`. This requires using a function that will possibly be hard-deprecated in the future so this needs some care
* pull out the compatibility layer from the vignette, and simplify the binary support detection

**Comment by richfitz** [comment]
SQLite has been updated on CRAN (with some breaking changes - #22, #31), so package should be updated to require the new version only.

**Comment by fmichonneau** [comment]
If you haven't done so (I haven't checked), I'm happy to work on a PR to update the vignette with the latest SQLite.

**Comment by richfitz** [comment]
Thanks - it's working in the current version; trying to get it running on travis properly though!

The next storr version includes proper DBI support but also a bunch of new stuff that will require me to rework the drivers vignette so much I've moved it aside for now (things are still backward compatible from the user point of view, but if anyone has written a custom driver things are going to break pretty hard -- but I don't think anyone has yet...)

**Comment by richfitz** [comment]
Fixed on develop branch
