### ISSUE TITLE
best practice for multi-argument hook

### ISSUE THREAD

**Issue by fmichonneau** [richfitz/storr#36]
Is there a way to do something like?

```r
st <- storr_external(driver_rds("data/foo"), ff)

ff <- function(key, namespace, some_other_data) {
   # some calculation that depends on some_other_data
}
```

In normal code, I could put `some_other_data` inside the `ff` function, but in this particular case `some_other_data` is a target from a remake project that takes a long time to compute.

**Comment by richfitz** [comment]
Can you do this via a closure?  Something like:

```r
make_hook <- function(some_other_data) {
  force(some_other_data)
  function(key, namespace) {
    # some function that uses some_other_data?
  }
}
```

Otherwise, I'm sure something could be done.  The implementation for the external storr is quite small so it would be easy enough to build from that to fit your use case better
