### ISSUE TITLE
Separate blob storage from key storage

### ISSUE THREAD

**Issue by richfitz** [richfitz/storr#67]
The use case here is large binary files and a shared filesystem

**Comment by wlandau-lilly** [comment]
Is this just for new backends, or will it extend to all drivers? `storr_rds()` already has separate key/blob storage, but you might have better drivers in mind for shared file systems.

**Comment by richfitz** [comment]
No, this would combine any two backends. The issue we have at work is a shared filesystem that plays poorly with lots of small file so I want to farm the key->hash map to Redis but keep the blob store part on disk
