### ISSUE TITLE
Possible CRAN violation - writing to disk

### ISSUE THREAD

**Issue by richfitz** [richfitz/storr#7]
See here https://github.com/hadley/rappdirs/issues/2#issuecomment-49665092

The rappdir's using components might need to get permission to write do disk.  Thoughts @wcornwell, @dfalster - this will be an issue for baad.data and taxonlookup.

Relevant section of CRAN policy is:

> - Packages should not write in the users’ home filespace, nor anywhere else on the file system apart from the R session’s temporary directory (or during installation in the location pointed to by TMPDIR: and such usage should be cleaned up). Installing into the system’s R installation (e.g., scripts to its bin directory) is not allowed.
> Limited exceptions may be allowed in interactive sessions if the package obtains confirmation from the user.

Which is frankly insane (especially given that we have function in R that write to the disk, like `pdf`).

**Comment by wcornwell** [comment]
Not sure I totally understand the discussion, but hadley seems to think it's alright?
https://github.com/hadley/rappdirs/issues/2#issuecomment-49665755

**Comment by richfitz** [comment]
Possibly but:

* checking before hand basically breaks packages for general use
* lots and lots of packages write to the disk without asking (beyond things like `pdf`, the packrat package does everything by writing to disk). 

I'm not sure that this is actually an issue, so much as a really stupid policy.

**Comment by drknexus** [comment]
https://github.com/HenrikBengtsson/R.cache writes to local disk and is also a caching layer. You might glance at how he gets approval from the user and where he writes the files for guidance.

**Comment by richfitz** [comment]
No longer depending on rappdirs here (see https://github.com/richfitz/datastorr for that) so this is no different to anything else that writes to disk explicitly.
